id = "decorative-stitch"
name = "Decorative Stitch Theme"
version = "1.0.0"
schema_version = 1
authors = ["keith <keith@keithrowell.com>"]
description = "Decorative Stitch theme for Zed. Subtle, sophisticated, pleasing to the eye and conducive to writing beautiful code."
repository = "https://github.com/keithrowell/zed-theme-decorative-stitch.git"
